# Generated by Django 3.1.7 on 2021-04-05 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinglecture',
            name='vote_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 16, 15, 27, 632894)),
        ),
    ]
