# Generated by Django 3.1.7 on 2021-04-02 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_pendinglecture_vote_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinglecture',
            name='vote_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 8, 18, 11, 850950)),
        ),
    ]
