# Generated by Django 3.1.7 on 2021-04-07 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('lecture', '0003_auto_20210407_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinglecture',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
