# Generated by Django 3.1.7 on 2021-04-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20210406_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='detail',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='image_url',
            field=models.CharField(max_length=250),
        ),
    ]
