# Generated by Django 3.1.7 on 2021-04-02 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20210402_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinglecture',
            name='cover_image_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='pendinglecture',
            name='summary_image_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='pendinglecture',
            name='thumbnail_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='pendinglecture',
            name='vote_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 8, 57, 15, 111793)),
        ),
    ]
