# Generated by Django 3.1.7 on 2021-04-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='image_url',
            field=models.CharField(default='image', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
