# Generated by Django 3.1.7 on 2021-04-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210406_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='image_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='profile_image_url',
            field=models.CharField(max_length=2000),
        ),
    ]
