# Generated by Django 3.1.7 on 2021-04-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210402_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(default='12', max_length=20),
            preserve_default=False,
        ),
    ]
